// Static image map — React Native requires static requires (no dynamic paths)
// Maps recipe IDs to local assets in assets/recipes/
const recipeImages: Record<string, any> = {
  // ── Breakfast ──
  b001: require('../assets/recipes/b001.png'),
  b002: require('../assets/recipes/b002.png'),
  b003: require('../assets/recipes/b003.png'),
  b004: require('../assets/recipes/b004.png'),
  b005: require('../assets/recipes/b005.png'),
  b006: require('../assets/recipes/b006.png'),
  b007: require('../assets/recipes/b007.png'),
  b008: require('../assets/recipes/b008.png'),
  b009: require('../assets/recipes/b009.png'),
  b010: require('../assets/recipes/b010.png'),
  b011: require('../assets/recipes/b011.png'),
  b012: require('../assets/recipes/b012.png'),
  b013: require('../assets/recipes/b013.png'),
  b014: require('../assets/recipes/b014.png'),
  b015: require('../assets/recipes/b015.png'),
  b016: require('../assets/recipes/b016.png'),
  b017: require('../assets/recipes/b017.png'),
  b018: require('../assets/recipes/b018.png'),
  // ── Lunch / Dinner ──
  ld001: require('../assets/recipes/ld001_butter_paneer_masala.jpg'),
  ld002: require('../assets/recipes/ld002_kadhai_paneer.jpg'),
  ld003: require('../assets/recipes/ld003_soya_masala.jpg'),
  ld004: require('../assets/recipes/ld004_rajma_chawal.jpg'),
  ld005: require('../assets/recipes/ld005_kadi_chawal.jpg'),
  ld006: require('../assets/recipes/ld006_dal_chawal.jpg'),
  ld007: require('../assets/recipes/ld007_sev_tamatar.jpg'),
  ld008: require('../assets/recipes/ld008_chole.jpg'),
  ld009: require('../assets/recipes/ld009_sprouts_ki_sabji.jpg'),
  ld010: require('../assets/recipes/ld010_paneer_ghee_roast.jpg'),
  ld011: require('../assets/recipes/ld011_bhindi.jpg'),
  ld012: require('../assets/recipes/ld012_cluster_beans.jpg'),
  ld013: require('../assets/recipes/ld013_methi_malai_paneer.jpg'),
  ld014: require('../assets/recipes/ld014_baingan_bharta.jpg'),
  ld015: require('../assets/recipes/ld015_paneer_bhurji.jpg'),
  ld016: require('../assets/recipes/ld016_jeera_aloo.jpg'),
  ld017: require('../assets/recipes/ld017_veg_pulao.jpg'),
  ld018: require('../assets/recipes/ld018_dum_aloo.jpg'),
  ld019: require('../assets/recipes/ld019_kala_chana.jpg'),
  ld022: require('../assets/recipes/ld022_dal_makhani.jpg'),
  ld023: require('../assets/recipes/ld023_vegetable_khichdi.jpg'),
  ld024: require('../assets/recipes/ld024_matar_paneer.jpg'),
  ld025: require('../assets/recipes/ld025_besan_gatta.jpg'),
  ld026: require('../assets/recipes/ld026_thepla.jpg'),
};

export default recipeImages;
